### ISSUE TITLE
GVRVideoView not recognized after (apparent) successful plugin creation

### ISSUE THREAD

**Issue by jsfgreen** [NativeScript/ios-runtime#826]
Related to [#597](https://github.com/NativeScript/ios-runtime/issues/597)

I tried to follow the instructions as closely as possible creating first a plugin to wrap google's 'GVRSDK' like so:

    $ tree GVRPlugin/
    GVRPlugin/
    ├── package.json
    └── platforms
        └── ios
            ├── Podfile
            └── build.xcconfig

My package.json

    {
      "name": "GVRPlugin",
      "version": "0.0.1",
      "nativescript": {
        "platforms": {
          "ios": "1.3.0"
        }
      }
    }

My build.xcconfig

    OTHER_LDFLAGS = $(inherited) -framework "CoreText"

My Podfile

    pod 'GVRSDK'

Then I added this custom plugin of mine to a test project called GVRTest like so

    $ tns create GVRTest --ng
    $ tns plugin add ../plugins/GVRPlugin

Then I followed instructions on [how to generate debug metadata here](https://docs.nativescript.org/runtimes/ios/how-to/use-native-libraries#troubleshooting).

The contents of my [typings/x86_64/objc!GVR.d.ts can be found here](https://gist.github.com/jsfgreen/41faf24dd64eeedb3be1af49f7236016#file-objc-gvr-d-ts).

And the contents of [metadata-x86_64/GVR.yaml here](https://gist.github.com/jsfgreen/41faf24dd64eeedb3be1af49f7236016#file-gvr-yaml).

I tried to instantiate a GVRVideoView object like so:

     let videoView = new GVRVideoView();

The app built successfully until I actually tried accessing the GVRSDK like in the previous snippet, as doing so gave me the following error in my console (terminal):

    app/video/video.component.ts(19,29): error TS2304: Cannot find name 'GVRVideoView'.

**Comment by jsfgreen** [comment]
I should add that I manually created a module.modulemap file for GVRSDK in `platforms/ios/Pods/Headers/Public/GVRSDK/module.modulemap`

The contents of that file are:

    module GVR {
      header "GVRAudioEngine.h"
      header "GVRCardboardView.h"
      header "GVRHeadTransform.h"
      header "GVROverlayView.h"
      header "GVRPanoramaView.h"
      header "GVRVideoView.h"
      header "GVRWidgetView.h"

      export * 
    }

And just in case, here are some versions of related stuff:

    node: v8.4.0
    npm: 5.5.1
    tns: 3.3.0
    Xcode: 9.1 Build version 9B55

**Comment by ginev** [comment]
@jsfgreen - can you try following the advice in this thread and see if it helps:
https://github.com/NativeScript/ios-runtime/issues/524#issuecomment-339743549

**Comment by jsfgreen** [comment]
@ginev I assume you mean the instructions in [this comment](https://github.com/NativeScript/ios-runtime/issues/524#issuecomment-194748217)?  I will do so, and it looks like using capital letters in plugin names is not recommended, I will also rename my plugin to `gvr-plugin`.

I saw [here](https://docs.nativescript.org/plugins/plugin-reference#use-a-plugin) that to use my plugin I have to `require()` it, so if my plugin will be called `gvr-plugin`, does that mean I require it with `require('gvr');` or `require('gvr-plugin');` or is none of that needed in {N} angular?  That part is still unclear to me anyway.

**Comment by ginev** [comment]
@jsfgreen - Yes, is that approach useful for you? As for the `require` call: depending on the name of the plugin as defined in your `package.json` file your `require()` call should use that name.

**Comment by jsfgreen** [comment]
I created a new project called `GVRTest2` and followed the instructions from #524 as you suggested and, again, the project builds but I can't use the plugin.  In items.component.ts I just put a simple `var gvr = require('gvr-plugin'); console.log(gvr);` and when I try to run with `tns run ios` I get this:

    CONSOLE ERROR [native code]: ERROR Error: Could not find module 'gvr-plugin'. Computed path '/Users/myuser/Library/Developer/CoreSimulator/Devices/771544B3-6CFC-400F-909C-33F481849E04/data/Containers/Bundle/Application/30191B73-2D22-4A82-9CB0-A47BA35115A9/GVRTest2.app/app/tns_modules/gvr-plugin'.
CONSOLE ERROR [native code]: ERROR CONTEXT [object Object]

**Comment by ginev** [comment]
@jsfgreen - can you please check if your plugin is correctly prepared, i.e. copied within the `tns_modules` folder inside the iOS platform folder of your NativeScript app (this is an example screenshot, your plugin should be in the `tns_modules` folder after tns prepare ios/tns run ios):

<img width="307" alt="tns_modules" src="https://user-images.githubusercontent.com/5871176/33374184-bd07fe7a-d50d-11e7-9788-584ad2c540c3.png">

**Comment by jsfgreen** [comment]
This is what I have:

<img width="288" alt="screen shot 2017-11-29 at 4 47 49 pm" src="https://user-images.githubusercontent.com/2606025/33403226-1e851e5a-d525-11e7-9aa4-e38523563bee.png">

**Comment by ginev** [comment]
@jsfgreen - this then leaves me without a guess of what might be the case here. I will need to directly take a look at the project you are attempting to use your plugin in. Would it be possible if you zipped it and attached it here for me to further investigate?

**Comment by jsfgreen** [comment]
@ginev Yes, absolutely, and I appreciate the help greatly. I will get right on that and post it momentarily.

**Comment by ginev** [comment]
Hello @jsfgreen,

1. You need to define an entry point for your plugin to be able to `require()` it. That said - you need an `index.js` file at root level within your plugin's structure.
2. I see the path in your `build.xcconfig` is not correct: `$(PROJECT_DIR)/../../node_modules/ga-plugin/platforms/ios/headers` must be `$(PROJECT_DIR)/../../node_modules/gvr-plugin/platforms/ios/headers`
3. Another problem that occurs only in the case where you install your plugin from a folder is with symlinks. NPM now uses symlinks to represent your plugin within the `node_modules` folder of your app. When the relative path in the `module.modulemap` is resolved the symlink breaks it and the location of the headers is not correctly obtained. You have two options - either manually copy the module.modulemap in the platforms/ios folder of the app where the XCode project resides or implement a hook that copies it each time the plugin is prepared. I am attaching here a sample plugin and an app that uses it that implement the hook scenario.
[plugin_pod_hook.zip](https://github.com/NativeScript/ios-runtime/files/1521395/plugin_pod_hook.zip)

I hope this is helpful.

**Comment by ginev** [comment]
@jsfgreen - you may find this sample here useful. I have prepared it covering the problem with symlinks and module maps: https://github.com/NativeScript/plugin-ios-modulemap-sample

**Comment by jsfgreen** [comment]
@ginev Thank you! Sorry for the long delay on replying; I ran into some issues with node/npm.  I ended up having to uninstall node/npm and my `/usr/local/lib/node_modules` and reintall nativescript.

Now my GVRTest2 project builds and I can successfully `require('gvr-plugin')` which is fantastic!  However, I still can't instantiate a `GVRVideoView()` object in my app.  Perhaps I am doing it wrong?

Again, in my items.component.ts:

    ngOnInit(): void {
        this.items = this.itemService.getItems();
        let gvr = require('gvr-plugin');
        console.log(gvr());
        let _vrVideoView = new GVRVideoView();
    }

And I get:

    app/item/items.component.ts(22,32): error TS2552: Cannot find name 'GVRVideoView'. Did you mean '_vrVideoView'?

Thanks again for all the help!

**Comment by ginev** [comment]
@jsfgreen - it seems the native types are yet not discovered by the NativeScript metadata generator. Can you zip your project and attach it here for further investigation?

**Comment by jsfgreen** [comment]
@ginev Sure.  I had to exclude `node_modules` and `platforms/ios` for the zip to be small enough.

[gvr_plugin_and_app.zip](https://github.com/NativeScript/ios-runtime/files/1528877/gvr_plugin_and_app.zip)

**Comment by ginev** [comment]
@jsfgreen - this error is a TypeScript error. Actually, if you turn off the `noEmitOnError` option in your `tsconfig.json` file you will be able to access the native types from your `gvr-plugin`. Also, you do not need to `require(\`gvr-plugin\`)` it unless you have additional JavaScript types you would like to use from it. The native types from the Pod are immediatelly available from within your app as soon as you install the plugin.

The TypeScript error is due to the fact that when using TypeScript you need to have a type definition for all types you are using throughout your app. `GVRVideoView` is not recognised as an existing class and therefore the TypeScript step fails with this error: `app/item/items.component.ts(22,32): error TS2552: Cannot find name 'GVRVideoView'. Did you mean '_vrVideoView'`.

To solve this problem you need to define a `.d.ts` file containing the types that you would like to use from GVRSDK. The NativeScript metadata generator can be used to generate those by supplying the following argument to its command line invocation:
`-output-typescript, './<path-to-output>'`

Since this seems to be an important topic for plugin developers that use native APIs, we will consider extending the docs with more information on how to use this.

For your convenience, I have generated the `.d.ts` file that exposes all GVRSDK native types and have added it into your project. Take a look at the attached `.zip` for more information.

I hope this is helpful.
[gvr_plugin_and_app.zip](https://github.com/NativeScript/ios-runtime/files/1530253/gvr_plugin_and_app.zip)

**Comment by jsfgreen** [comment]
@ginev You, sir, are a gentleman and a scholar! I will surely try this right away and let you know how it turns out.  Thanks again for everything!

**Comment by etabakov** [comment]
Closing this issue as resolved.
