### ISSUE TITLE
No indenting in console.dir() object dump

### ISSUE THREAD

**Issue by aaayushsingh** [NativeScript/ios-runtime#911]
### Issue: 
There is no indenting in the console.dir object dump on iOS devices. See image below.

I'd like to work on this issue and submit a PR.

<img width="1176" alt="screen shot 2018-04-11 at 2 03 34 pm" src="https://user-images.githubusercontent.com/19550852/38658530-3845a08a-3e43-11e8-9185-5dc54d6f416e.png">

### Version numbers that your issue occurs with:

- CLI: 4.0.0-2018-04-05-11381
- Cross-platform modules: 3.4.1
- Runtime(s): iOS - 4.0.1-rc-2018-04-05-01
- Plugin(s): NA

### Steps to reproduce

1. create new project with hello world template.
2. paste this anywhere in the files...
```
console.dir({
    name1: "value1",
    name2: "value2",
    name3: {
      name3_1: "value3_1",
      name3_2: "value3_2",
      name3_3: {
        name3_3_1: "value",
        name3_3_2: "value"
      }
    }
  });
```

**Comment by aaayushsingh** [comment]
I was working on this but there was a commit by someone that appeared to have fixed this issue. I'll get onto this of no-one else is.

**Comment by mbektchiev** [comment]
@aaayushsingh, thank you for the willingness to help. We've checked that this still is not fixed, so you can continue with it if you want.

**Comment by aaayushsingh** [comment]
sure. I'm on it then

**Comment by aaayushsingh** [comment]
> I was working on this but there was a commit by someone that appeared to have fixed this issue.

@mbektchiev I can't reproduce this when I add the ios runtime like the readme. That way everything logs fine. This why I thought it was fixed already

**Comment by mbektchiev** [comment]
@aaayushsingh I just found out that indeed it's fixed. PR #884 has addressed it. I'm really sorry for misleading you.

**Comment by mbektchiev** [comment]
@aaayushsingh Thank you very much for willing to help us. If you feel it suits you, you may work on the other issue that is marked with [help wanted](https://github.com/NativeScript/ios-runtime/labels/help%20wanted). It is suitable for first time committers as well.

**Comment by Natalia-Hristova** [comment]
I still reproduce it with `CLI: 5.0.0` and `ios-runtime: 5.0.0` on simulator and device.

**Comment by aaayushsingh** [comment]
@Natalia-Hristova yeah, It is reproducible with NativeScript cli but when I try to reproduce using steps mentioned [here](https://github.com/NativeScript/ios-runtime/issues/911#issuecomment-421935097) in comment by @mbektchiev and run using xcode, the log is indented properly.

**Comment by mbektchiev** [comment]
@aaayushsingh @Natalia-Hristova I've tested and can confirm that the iOS Runtime actually indents the output, but it seems like there's some trimming happening in {N} CLI. We will move the issue to the CLI repository. Thank you both for helping clear this out!

**Comment by tsonevn** [comment]
Issue moved to [NativeScript/nativescript-cli #4160](https://github.com/NativeScript/nativescript-cli/issues/4160) via [**ZenHub**](https://www.zenhub.com/)
